theme: jekyll-theme-midnight
title: Huddle
description: Fully local, no servers, no 3rd party connections, just the connections you'll make with your friends and family. 
show_downloads: false
# google_analytics: G-NGHPT02Y6B
