theme: jekyll-theme-midnight
title: Huddle
description: Introducing our new iOS app, "Huddle"! Huddle is a unique social networking app that focuses on helping you connect with your loved ones in person and share personal posts with them. With Huddle, you can create a private network of friends and family that is completely offline and secure.
show_downloads: false
# google_analytics: G-NGHPT02Y6B
